version: '2'
services:
 cassandra:
  image: cassandra:2.2
  ports:
   - "9042:9042"
  container_name: "cassandra"

 kafka:
  image: landoop/fast-data-dev
  ports:
   - "2181:2181"
   - "3030:3030"
   - "8081:8081"
   - "8082:8082"
   - "8083:8083"
   - "9092:9092"
  environment: 
    ADV_HOST: 10.14.8.38
  container_name: "kafka"

 spark-master:
  image: sequenceiq/spark:1.6.0
  mem_limit: 2000000000
  ports:
   - "8088:8088"
   - "8042:8042"
   - "5005:5005"
   - "4040:4040"
  depends_on:
   - cassandra
   - kafka
  volumes:
   - ./enron-consumer/target:/app
  environment:
    KAFKA_BROKERS: kafka:9092
    KAFKA_TOPICS: enron-mails
    KAFKA_SCHEMA_REGISTRY: http://10.14.8.38:8081
    KAFKA_OFFSET_RESET: smallest
    KAFKA_FETCH_BYTES: 10000000
    CASSANDRA_HOST: cassandra
  command: export SPARK_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 && spark-submit --class com.fjbecerra.initialize.EnronInizializer --driver-memory 1G --executor-memory 1G /app/enron-consumer-0.0.1-SNAPSHOT-jar-with-dependencies.jar \
     && spark-submit --class com.fjbecerra.event.EnronEventStreamJob --driver-memory 1G --executor-memory 1G /app/enron-consumer-0.0.1-SNAPSHOT-jar-with-dependencies.jar
  container_name: "spark-master"
  

 enron-connector:
  image: frolvlad/alpine-oraclejdk8:slim
  ports:
   - "8086:8080"
  depends_on:
   - kafka
   - logstash
  volumes:
    - ./enron-connector/target:/app
    - /enron:/enron/input
    - /tmp/
  environment:
    KAFKA_BROKERS: kafka:9092
    KAFKA_TOPICS: enron-mails
    KAFKA_SCHEMA_REGISTRY: http://10.14.8.38:8081
    KAFKA_BATCH_SIZE: 10000000
    KAFKA_REQUEST_SIZE: 10000000    
    KAFKA_MESSAGE_MAX_SIZE: 10000000
    ENRON_INPUT_FILES: enron/input
  command: java -jar /app/enron-connector-0.0.1-SNAPSHOT.jar
  container_name: "enron-connector"
   
 zeppelin:
   image: richardkdrew/zeppelin 
   ports:
    - "8080:8080"
    - "8085:8081"
   depends_on:
    - cassandra   
   container_name: zeppelin

 elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"    
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"    
    container_name: elasticsearch

 kibana:
   image: kibana  
   ports:
     - "5601:5601"   
   depends_on:
     - elasticsearch
   environment:
    ELASTICSEARCH_URL: http://10.14.8.38:9200
   container_name: kibana

 logstash:
   build: logstash
   command: logstash -f /conf/logstash-spring-boot.conf
   ports:
     - "5514:5514"   
   depends_on:
     - elasticsearch
   container_name: logstash
  


